export default {
  lang: "es",
  si: "Sí",
  no: "No",
  /* Navbar */
  inicio: "Inicio",
  nosotros: "¿Quiénes somos?",
  actualidad: "Actualidad",
  servicios: "Servicios",
  contacto: "Contacto",

  /* Inicio */
  ver_actualidad: "Ver todas las publicaciones",
  leer_mas: "Leer más",
  categorias: "Compite en tus categorías favoritas",
  ver_mas: "Ver más",
  ver_menos: "Ver menos",

  /* Footer */
  keep_connected: "Mantente conectado con nosotros en redes sociales",
  sobre_nosotros: "Sobre nosotros",
  ayuda: "Ayuda",
  tos: "Términos y condiciones",
  faq: "Preguntas frecuentes",
  privacy: "Política de privacidad",
  copyright: "Todos los derechos reservados",
  ultimo: "¡Lo último!",

  /* Servicios */
  eventos: "Organización de eventos Esports",
  streaming: "Producción de streaming",
  branding: "Branding y Asesoría",
  casters: "Casters y Hosts Esports",
  /* Servicios: Eventos */
  eventos_p1: "<i><strong>EXPERIENCIA, INNOVACIÓN Y CALIDAD</strong></i>. Comprometidos con el éxito, organizamos eventos gaming, torneos y ligas, totalmente personalizados y ajustados a la medida de lo que su marca está buscando. Con experiencia en todas las categorías de juegos, abarcando todas las plataformas: pc, consola y móvil.",
  eventos_p2: "Nuestro alto compromiso con nuestros clientes y gamers, nos ha llevado a la innovación constante, adaptándonos a las nuevas tendencias nacionales e internacionales, llevándoles una experiencia gamer única, superando sus expectativas y proyecciones.",
  /* Servicios: Streaming */
  streaming_p1: "<i><strong>GESTIÓN, PRODUCCIÓN Y CREATIVIDAD</strong></i>. Somos especialistas en producción Esports. El streaming es una de las partes más importantes de todo evento Esports, es donde realmente se conecta con el público.",
  streaming_p2: "En PESP contamos con todo el equipo técnico para la realización de transmisiones de alta calidad, ya sean de manera virtual o presencial, y con el equipo de expertos en transmisiones de todas las categorías de juegos, logrando el nivel profesional y la atracción que está buscando para su marca, con la suficiente vistosidad y entretenimiento para el público en línea y en vivo.",
  /* Servicios: Branding */
  branding_p1: "<i><strong>COMPROMISO Y RESPONSABILIDAD</strong></i>. Nuestra motivación está centrada en lograr su satisfacción.",
  branding_p2: "Ofrecemos asesoría personalizada en todo momento para desarrollar un evento tematico, innovador y totalmente personalizado que conecte con su marca y se ajuste a sus necesidades y proyecciones.",
  branding_p3: "Basados en uno de nuestros principios más importantes, compromiso y responsabilidad, nuestros clientes hablan por sí solos, obteniendo un 100% de preferencia por Marcas y Gamers.",
  /* Servicios: Casters */
  casters_p1: "<i><strong>MOTIVACIÓN Y CONOCIMIENTO TÉCNICO</strong></i>. Sentimos pasión por los Esports.",
  casters_p2: "Llevamos la acción, el entretenimiento y el conocimiento técnico gracias a nuestro equipo de comentaristas y presentadores especializados y entrenados en las distintas categorías de juegos, para ofrecerles un Show de altura.",
  casters_p3: "Conecta con el público joven y vive la emoción de los Esports, minuto a minuto de la mano de los expertos.",
  /* Servicios: Casos de éxito */
  casos_exito: "Casos de éxito",
  ce_gravitycup: "Evento estrella Esports de LG ULTRAGEAR, desarrollado de manera virtual, por PESP en el 2021, con torneos clasificatorios en 2 categorías de juegos, en pc y consola, con su eslogan “los mejores jugadores, juegan con los mejores monitores, LG ULTRAGEAR, logra posicionarse entre un público selectivo, exigente y competitivo como los monitores gaming favoritos, que todo gamer debe tener y una de las marcas favoritas en Panamá que siempre apoya el gaming.",
  ce_yoytecgamerfest: "Festival gamer y tecnológico de YOYTEC, empresa de ventas de tecnología en Panamá, organizado por PESP, en La Universidad Tecnológica de Panamá, con más de 2.000 asistentes, más de 9.000 dólares en premios y más de 15 marcas gaming patrocinadoras, como AOC, PRIMUS, DELL, MSI, LOGITECH, COOLER MASTER, CORSAIR, DXRACER, RAZER, HYPERX, HP, entre muchas otras, YOYTEC apuesta por los Esports, logrando posicionarse como el favorito entre el público joven.",
  ce_mesgamer: "En celebración al día del gamer, “Mes Gamer”, es un Producto creado por PESP, en el 2019 especialmente para todos los gamers, desarrollado durante todo el mes de agosto, ya cuenta con 2 ediciones exitosas. Imagina todo un mes lleno de activaciones, torneos, giveaway, premios y muchas sorpresas, con cierre en un gran evento virtual con transmisión online, especialmente para los Gamers, patrocinado por distintas marcas como Yoytec, Logitech, entre muchas otras, ¿por qué solo celebrar un día si puedes celebrar todo un mes?",
  /* Servicios: Estadísticas */
  experiencia: "Años de experiencia",
  actividades: "Actividades realizadas",
  pc: "Competencias en PC",
  consola: "Competencias en consola",
  mobile: "Competencias en móvil",
  /* Servicios: Marcas */
  confian: "Ellos confían en nosotros",
  patrocina: "Marcas patrocinadoras de nuestros eventos",

  /* Quienes somos */
  somos: "¡Somos PESP!",
  calidad: "Experiencia, Innovación Y Calidad",
  apoyando: "Apoyando el talento gamer",
  /* Quienes somos: Nosotros */
  nosotros_p1: "<i><strong>Panamá Esports Productions (PESP)</strong></i>, una empresa Esports, con más de 5 años de experiencia.",
  nosotros_p2: "Nos dedicamos a la organización de eventos, torneos, ligas y producción de streaming gaming en modalidad virtual o presencial, con experiencia en todas las categorías de juegos, abarcando todas las plataformas: PC, consola y móvil.",
  nosotros_p3: "Comprometidos con el éxito, contamos con un equipo de trabajo especializado en Esports, brindándole a nuestros clientes la mejor calidad y satisfacción en todas sus proyecciones y a nuestros usuarios las mejores experiencias gaming competitivas.",
  /* Quienes somos: Calidad */
  calidad_p1: "Nuestra misión se basa en tres pilares fundamentales: <i><strong>Experiencia, Innovación y Calidad</strong></i>.",
  calidad_p2: "Cada acción está basada en la creación de eventos y experiencias innovadoras y personalizadas, desarrolladas por nuestro equipo de especialistas Esports, cumpliendo con los más altos estándares de calidad y producción, satisfaciendo y superando las expectativas de nuestros clientes, gamers y espectadores.",
  calidad_p3: "Todo esto desarrollado en un ambiente profesional, pero con la suficiente emoción y pasión que nos caracteriza.",
  /* Quienes somos: Apoyando */
  apoyando_p1: "Uno de nuestros objetivos es <i><strong>Apoyar el Talento Gamer</strong></i>, impulsando los deportes electrónicos (Esports), en Panamá y en Latinoamérica, desarrollando y creando un espacio profesional y atractivo que influya de manera positiva en la juventud.",
  apoyando_p2: "A través de nuestra gestión y promoción cultural Esports, hacemos énfasis en la educación integral y el avance tecnológico, utilizados como herramientas principales, sentando las bases que permitan obtener un crecimiento reflejado en el conocimiento, economía, tecnología y oportunidad laboral.",
  /* Comentarios */
  comentarios: "Comentarios",
  comentario_lg: "Estamos muy contentos y agradecidos de trabajar ya hace varios años con PESP en torneos y actividades para nuestros monitores LG UltraGear.  Su trabajo es de primera calidad y su equipo es 100% profesional, superando las expectativas! Trabajo 100% recomendado.",
  comentario_yoytec: "Realmente valoramos y felicitamos al equipo de PESP, por todo el apoyo y buen servicio que nos han brindado desde el 2019, trabajando juntos. Su constante innovación, profesionalismo, conocimiento y pericia en Esports, nos han brindado resultados satisfactorios en cada proyecto realizado. Apostamos que lograrán cada objetivo que se propongan, por su gran pasión y esfuerzo que los caracteriza. ¡Felicidades chicos, vamos por más!.",
  comentario_vsg: "Desde nuestros inicios, PESP ha sido uno de nuestros mejores aliados en nuestra misión de impulsar el universo Gamer, contagiando la pasión a más y más jugadores.",
  comentario_gamerton: "Como organizador de la GamerTon 20-30 me sentí en todo momento respaldado de excelentes profesionales como los de PESP. Este equipo de trabajo de jóvenes tienen la mejor experiencia y dedicación en Panamá para llevar eventos de Esports al más alto nivel.",
  comentario_loltec: "Nuestra experiencia con PESP ha sido excelente, y lo que hace la diferencia al organizar eventos es su planificación, al establecer un plan de trabajo y cumplir las métricas al 100%, podemos estar confiados que saldrá bien, por su gran equipo de trabajo y conocimiento.",
  /* Galería */
  galeria: "Galería",

  /* Contacto */
  contacto_info: "¡Nuestro equipo está preparado para ayudarte en todo momento y responder cualquier duda o consulta!",
  contacto_title: "Llena el siguiente formulario para contactarnos",
  contacto_desc: "Y te responderemos a la brevedad posible, vía correo electrónico.",
  nombre: "Nombre",
  nombre_full: "Nombre completo",
  correo: "Correo electrónico",
  mensaje: "Mensaje",
  enviar: "Enviar",
  asunto: "Asunto",
  unirse_title: "Este es el primer paso para ser PESP",
  unirse_desc: "Nuestro equipo se pondrá en contacto contigo vía correo electrónico.",
  porque_pesp: "¿Por qué quieres ser parte de PESP?",
  cuentanos: "Cuéntanos más sobre ti",
  mayor: "¿Eres mayor de edad?",
  correo_enviado: "El correo ha sido enviado exitosamente",
  correo_error: "Ha ocurrido un error al enviar el correo",

  /* Mail Templates */
  equipo_pesp: "Equipo PESP",
  correo_recibido: "¡Hemos recibido tu formulario de contacto! Nuestro equipo pronto se pondrá en contacto con usted a través de esta conversación de correo electrónico.",
  mientras_esperas: "Mientras esperas",
  visita_nuestra_web: "visita nuestro sitio web",
  informacion_enviada: "Información enviada",
  correo_informacion: "La siguiente información ha sido enviada a través de la página de contacto de PESP.",
  correo_footer: "Esta comunicación contiene información que es confidencial y también puede contener información privilegiada. Es para uso exclusivo del destinatario/s. Si usted no es el destinatario/s tenga en cuenta que cualquier distribución, copia o uso de esta comunicación o la información que contiene está estrictamente prohibida. Si usted ha recibido esta comunicación por error por favor notifíquelo por correo electrónico.",
  quieres_unirte: "¿Quiéres unirte a nuestro equipo?",
  asunto_interesado: "está interesado en unirse al equipo PESP",

  /* Actualidad */
  recientes: "Publicaciones recientes",
  actualidad_info: "Mantente actualizado(a) y conoce todas las novedades de PESP, actividades, eventos y torneos que desarrollamos especialmente para ti.",
  publicado_el: "Publicado el",
  abrir: "Abrir",

  /* SEO */
  home_keywords: "pespgg, panama, esports, pesp.gg, gamers, gaming, experiencia, profesionales",
  home_description: "Panama Esports Productions, la mejor experiencia gaming. Apoyando el Talento Gamer.",
  actualidad_keywords: "actualidad, panama, noticias, eventos, torneos",
  actualidad_description: "Mantente actualizado(a) y conoce todas las novedades de PESP, actividades, eventos y torneos que desarrollamos especialmente para ti.",
  contacto_keywords: "contacto, unirse, dudas, preguntas, pesp.gg",
  contacto_description: "Ponte en contacto con nosotros, y te responderemos a la brevedad posible, vía correo electrónico.",
  nosotros_keywords: "nosotros, quienes, somos, pesp.gg, conócenos, panama, esports, experiencia, calidad, innovación",
  nosotros_description: "Conoce más sobre nosotros, quienes somos, nuestra experiencia, calidad e innovación.",
  post_keywords: "post, publicación, pesp.gg, panama, esports, actualidad, noticias, eventos, torneos",
  faq_keywords: "faq, preguntas, respuestas, frecuentes, pesp.gg, panama, esports, eventos, torneos",
  faq_description: "Preguntas frecuentes sobre PESP",

  /* Admin */
  publicar: "Publicar",
  previsualizar: "Previsualizar",
  titulo: "Título de la publicación",
  config: "Configuración",
  tag: "Etiqueta",
  permalink: "Permalink",
  seleccionar: "Seleccionar",
  juegos: "Juegos",
  otros: "Otros",
  banner: "Banner",
  fecha: "Fecha",
  volver_editor: "Volver al editor",
  login: "Iniciar sesión",
  usuario: "Usuario",
  pass: "Contraseña",
  admin: "Admin",
  publico: "Público",
  visibilidad: "Visibilidad",
  oculto: "Oculto",
  confirm_delete_post: "¿Estás seguro que deseas eliminar esta publicación?",
  acciones: "Acciones",
  actualidad_admin_description: "En esta sección podrás editar y eliminar publicaciones de actualidad.",
  visitas: "Visitas",
  amenazas: "Amenazas",
  visitas_unicas: "Visitas únicas",
  visitas_en: "Visitas en los",
  dashboard: "Dashboard",
  estadisticas: "Aquí podrás ver las estadísticas generales del dominio y subdominios.",
  pais_region: "País / Región",
  solicitudes: "Solicitudes",
  desconocido: "Desconocido",
  browser: "Navegador",
  max_unique: "Máximo de visitas únicas",
  min_unique: "Mínimo de visitas únicas",
  por_dia: "Por día",
  ultimos_7_dias: "Últimos 7 días",
  ultimos_14_dias: "Últimos 14 días",
  ultimos_30_dias: "Últimos 30 días",
  logout: "Salir",
  correo_vinculado: "Correo vinculado",
  correo_corporativo: "Correo corporativo",
  correo_personal: "Correo personal",
  publicar_success: "¡Publicación creada exitosamente!",
  guardar_success: "¡Publicación guardada exitosamente!",
  oss: "Sistemas Operativos",

  /* Errors */
  unauthorized: "No autorizado",
  unsupported_media: "Tipo de archivo no soportado",
  file_too_large: "El archivo es demasiado grande",
  login_error: "Usuario o contraseña incorrectos",
  bad_request: "Solicitud incorrecta",
  token_not_provided: "Token no proporcionado",
  conflict: "Conflicto",
  post_not_found: "Publicación no encontrada",
  error: "Error inesperado",

  /* FAQ */
  faq_q1: "¿Quiénes somos?",
  faq_a1: "Panamá Esports Productions (PESP), primera productora gaming en Panamá, somos una empresa especializada en Esports, Nos dedicamos a la organización de eventos, torneos, ligas y producción de streaming gaming en modalidad virtual o presencial, con experiencia en todas las categorías de juegos, abarcando todas las plataformas: PC, consola y móvil.",
  faq_q2: "¿Qué tipo de competencias realizamos?",
  faq_a2: "En PESP, realizamos distintas competencias de diferente nivel, abiertas para toda la escena gamer y también Esports.",
  faq_q3: "¿Desde hace cuánto realizan competencias?",
  faq_a3: "Tenemos experiencia desde hace mas de {{ age }} años, realizando eventos, torneos, competencias, activaciones y asesorando a distintas empresas de la escena.",
  faq_q4: "¿Puedo participar en sus competencias?",
  faq_a4: "¡Claro que sí, es lo que queremos! Recuerda que siempre podrás participar en las competencias organizadas por PESP siempre y cuando cumplas todos los requisitos del reglamento ¡recuerda leerlo!",
  faq_q5: "¿Podemos trabajar en conjunto en una actividad?",
  faq_a5: "Por su puesto, envíanos un correo y te responderemos cuanto antes, nuestro equipo está capacitado para responder todas tus consultas o dudas.",
  faq_q6: "¿Quiénes conforman PESP?",
  faq_a6: "Panama Esports Productions (PESP) está conformado por un equipo de jóvenes expertos en Esports desarrollados en distintas ramas profesionales como marketing, legal, organizadores de torneos, árbitros, animadores, diseñadores, programadores, productores musicales, directores de streaming, host, casters y entre muchas otras profesiones que trabajan fuertemente en el desarrollo de la escena competitiva y gamer en Panamá y la región.",
  faq_q7: "¿Quién creó PESP?",
  faq_a7: "El fundador de Panamá Esports Productions, es conocido como “Zako” (Zadquiel Montenegro), jugador, organizador de competencias, empresario, una persona que ha tenido la visión y fe en los Esports desde hace más de 6 años buscando realzar y enaltecer este deporte en Panamá y Latinoamérica. si tienes alguna duda o consulta puedes contactarlo a su <a class=\"fw-bold\" href=\"https://www.linkedin.com/in/zadquiel-montenegro-8517951a6/\" target=\"_blank\">LinkedIn</a>.",

  /* Boletín Informativo */
  boletin_title: "Suscríbete a nuestro Boletín Informativo",
  boletin_description: "¡Y entérate de todos los eventos y torneos que PESP trae para ti, de forma exclusiva!",
  boletin_interests: "Selecciona tus intereses",
  boletin_tos: "Al marcar esta casilla, confirma que ha leído y está de acuerdo con nuestros <a href=\"/tos\" target=\"_blank\"><u>Términos de Uso</u></a> con respecto al almacenamiento de los datos enviados a través de este formulario.",
  boletin_suscribe: "Suscribirse",
  boletin_success: "¡Gracias por suscribirte a nuestro boletín informativo!",

  /* Compartir */
  copy_link: "Copiar enlace",
  link_copied_to_clipboard: "Enlace copiado al portapapeles",
  share: "Compartir",
  lets_share: "Comparte",
  send: "Enviar",
  post: "Publicar",
  copy_not_supported: "Copiar no está disponible en tu navegador"
};
